### ISSUE TITLE
镜像完美运行，但是是不是忘记将onnx导出rknn了

### ISSUE THREAD

**Issue by skywalkerjc** [c0zaut/rkllm-mm-export#1]
镜像完美运行，但是是不是忘记将onnx导出rknn了，运行完后只找到了onnx，我看了下py脚本也没有导出rknn的代码，我在容器中手动导出成功的

**Comment by c0zaut** [comment]
That's weird! I have the onnx -> rknn export here: https://github.com/c0zaut/rkllm-mm-export/blob/6740d33463774b6ed859ba3ab62e8c120db97693/export_vision.py#L69-L75

I definitely think there may be something funky happening with memory management - given some of the behavior I have seen, things are definitely a little leaky.

**Comment by skywalkerjc** [comment]
@c0zaut 找到问题了，你的rknn导出路径和rkllm是一样的，都是savepath = f'./rknn/{quantize.model_name}.rkllm' ，所以先导出的rknn被后面的rkllm覆盖了

**Comment by c0zaut** [comment]
Yep! That seems like the issue! I will push an uodate tonight to correct it!

**Comment by c0zaut** [comment]
Here you go!

https://github.com/c0zaut/rkllm-mm-export/commit/7244f803eff483a7e324fe1ef539ed4e5e8990ed
